/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTopicsRouteImport } from './routes/app.topics'
import { Route as AppQuizRouteImport } from './routes/app.quiz'
import { Route as AppPerformanceRouteImport } from './routes/app.performance'
import { Route as AppMaterialsRouteImport } from './routes/app.materials'
import { Route as AppChatRouteImport } from './routes/app.chat'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppTopicsIdRouteImport } from './routes/app.topics.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTopicsRoute = AppTopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizRoute = AppQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => AppRoute,
} as any)
const AppPerformanceRoute = AppPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AppRoute,
} as any)
const AppMaterialsRoute = AppMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppTopicsIdRoute = AppTopicsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppTopicsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/admin': typeof AppAdminRoute
  '/app/chat': typeof AppChatRoute
  '/app/materials': typeof AppMaterialsRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/quiz': typeof AppQuizRoute
  '/app/topics': typeof AppTopicsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/topics/$id': typeof AppTopicsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/admin': typeof AppAdminRoute
  '/app/chat': typeof AppChatRoute
  '/app/materials': typeof AppMaterialsRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/quiz': typeof AppQuizRoute
  '/app/topics': typeof AppTopicsRouteWithChildren
  '/app': typeof AppIndexRoute
  '/app/topics/$id': typeof AppTopicsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/admin': typeof AppAdminRoute
  '/app/chat': typeof AppChatRoute
  '/app/materials': typeof AppMaterialsRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/quiz': typeof AppQuizRoute
  '/app/topics': typeof AppTopicsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/topics/$id': typeof AppTopicsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/admin'
    | '/app/chat'
    | '/app/materials'
    | '/app/performance'
    | '/app/quiz'
    | '/app/topics'
    | '/app/'
    | '/app/topics/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/admin'
    | '/app/chat'
    | '/app/materials'
    | '/app/performance'
    | '/app/quiz'
    | '/app/topics'
    | '/app'
    | '/app/topics/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/admin'
    | '/app/chat'
    | '/app/materials'
    | '/app/performance'
    | '/app/quiz'
    | '/app/topics'
    | '/app/'
    | '/app/topics/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/topics': {
      id: '/app/topics'
      path: '/topics'
      fullPath: '/app/topics'
      preLoaderRoute: typeof AppTopicsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quiz': {
      id: '/app/quiz'
      path: '/quiz'
      fullPath: '/app/quiz'
      preLoaderRoute: typeof AppQuizRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/performance': {
      id: '/app/performance'
      path: '/performance'
      fullPath: '/app/performance'
      preLoaderRoute: typeof AppPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/materials': {
      id: '/app/materials'
      path: '/materials'
      fullPath: '/app/materials'
      preLoaderRoute: typeof AppMaterialsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/topics/$id': {
      id: '/app/topics/$id'
      path: '/$id'
      fullPath: '/app/topics/$id'
      preLoaderRoute: typeof AppTopicsIdRouteImport
      parentRoute: typeof AppTopicsRoute
    }
  }
}

interface AppTopicsRouteChildren {
  AppTopicsIdRoute: typeof AppTopicsIdRoute
}

const AppTopicsRouteChildren: AppTopicsRouteChildren = {
  AppTopicsIdRoute: AppTopicsIdRoute,
}

const AppTopicsRouteWithChildren = AppTopicsRoute._addFileChildren(
  AppTopicsRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppChatRoute: typeof AppChatRoute
  AppMaterialsRoute: typeof AppMaterialsRoute
  AppPerformanceRoute: typeof AppPerformanceRoute
  AppQuizRoute: typeof AppQuizRoute
  AppTopicsRoute: typeof AppTopicsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppChatRoute: AppChatRoute,
  AppMaterialsRoute: AppMaterialsRoute,
  AppPerformanceRoute: AppPerformanceRoute,
  AppQuizRoute: AppQuizRoute,
  AppTopicsRoute: AppTopicsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
